targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/bloc/**/*.dart
        options:
          format: false
      auto_route_generator:auto_router_generator:
        options:
          ignore_for_file:
            - inference_failure_on_instance_creation
        generate_for:
          - lib/router/router.dart
